#!/usr/bin/env perl

###################
#
# meeting-log-mailer
#
#	Ben Cotton
#	<bcotton@fedoraproject.org>
#
#	A script to automatically send the minutes from a MeetBot-recorded meeting.
#
#		Requirements:	Config::IniFiles (CPAN module)
#						LWP::Simple (CPAN module)
#						Term::Prompt (CPAN module)
#		Args:	newini [ini file]  OR [ini file] <URL> <group>
#		Input:	$HOME/.meeting-log-mailer.ini
#		Output:	$HOME/.meeting-log-mailer.ini (when called with newini)
#				email
#
###################

use strict;
use Config::IniFiles;
use LWP::Simple;
use Term::Prompt;

# I don't expect version number to change very often, but we might as well
# keep track of it, just in case.
my $VERSION = '0.0.nonfunctional';

# The default path for the ini file. This can be overridden by specifying a 
# filename as the first argument.
my $iniFile = $ENV{'HOME'} . '/.meeting-log-mailer.ini';

# The command used to send mail. We expect something roughly sendmail-like, but
# anything you want to use is fine by me. By default, I just ask for sendmail.
# If you don't want to change the setting here, you can specify 'sendmail' in 
# the [global] section of the ini file.
chomp(my $sendmail = `which sendmail`);

# Arguments given to the mail program. Again, something approximating sendmail
# options are expected. This setting can be overwritten by specifying 
# 'sendmailopts' in the [global] section on the ini file.
my $sendmailopts = '';

# Here's where we start doing things.

# Check to see if we're being run as root and die if we are. Nothing good can
# ever come of running this script as root.
if ( $< == 0 ) { 
	print STDOUT "Nothing good can ever come of running this as root\n\n"; 
	exit 1;
}

# Check to see if we were called with 'newini'. If we were check to see if a
# filename was given to use instead of the default and then ignore subsequent
# arguments. This, of course, means that naming an ini file 'newini' is an
# incredibly ungood thing to do.
if ( $ARGV[0] eq 'newini' ) { 
    if ( $#ARGV == 1 ) { $iniFile = $ARGV[1]; }
	print "Called with newini, preparing to create a new ini file\n";
	&newini;
}

# Were we called with three arguments? If so, the first one is a non-default 
# ini file to use. Set that first.
if ( $#ARGV == 2 ) { 
	$iniFile = shift @ARGV;
}

# If the ini file doesn't exist or can't be read, it will be difficult to get
# the configuration values from it.
if ( ! -r $iniFile ) {
	print STDOUT "Could not find the specified configuration file:\n\t";
	print STDOUT "$iniFile\nTry generating one with:\n\t $0 newini\n";
	print STDOUT "or specify a file that exists\n\n";
	exit 1;
}

# Do we have two arguments? The first should be the URL of the MeetBot minutes,
# and the second should be the group as specified in the ini file.
if ( $#ARGV != 1 ) {
	print STDOUT "Invalid number of arguments. I need exactly two:\n";
	print STDOUT "1. The URL of the MeetBot minutes (.txt)\n2. The group\n";
	exit 1;
}

# Now we set the URL and the group
my $url = shift @ARGV;
my $group = shift @ARGV;

# Here comes the hard part. Let's read the INI file and load whatever
# configuration we need to use.

my $config = new Config::IniFiles( -file => "$iniFile", -default=>"global" ); 

# Grab the specified log file or die
unless ( is_success(
	getstore("$url", "/tmp/m-l-m_minutes_$$") ) ) {

	die "Could not download $url to /tmp/m-l-m_minutes_$$";
}

# Start 

#########
#
# newini subroutine
#
#        Create a new ini file or blow away the old one
#
#########

sub newini {

	# Open the ini file. If we can't write to it, that's a problem.
	open (INIFILE, ">$iniFile") or die "Could not open $iniFile for writing\n";
	
	# Ask a few questions
	# Sender's email address?
	my $senderEmail = prompt('x', 'Your email address', '', '');
	# Senders name
	my $senderName = prompt('X', 'Your name', '', '');
	# cc aaddress
	my $ccEmail = prompt('X', 'Address(es) to cc', '', '');
	# Path to sendmail
	my $sendmail = prompt('X', 'Path to sendmail binary', '', "$sendmail");
	# Sendmail options
	my $sendmailopts = prompt('X', 'Sendmail options', '', "$sendmailopts");

	# Have the user define a group
	print "We will now define your first group. Multiple groups can be configured by\n";
	print "editing your ini file.\n";
	# The name of the group to use as the section ID
	my $groupName = prompt('a', 'Group name', 'Alpha only', '');
	# The groups email list
	my $groupEmail = prompt('x', 'Group email address', '', '');
	
	# Okay, let's get down to writing the file we've been keeping open.
	select(INIFILE);
	print "[global]\n";
	print "senderEmail = $senderEmail\n";
	if ( $senderName ) { print "senderName = $senderName\n"; }
	if ( $ccEmail ) { print "ccemail = $ccEmail\n"; }
	if ( $sendmail ) { print "sendmail = $sendmail\n"; }
	if ( $sendmailopts ) { print "sendmailopts = $sendmailopts\n"; }
    print "[$groupName]\ngroupemail = $groupEmail\n";

	close (INIFILE);
	select(STDOUT);

	exit 0;
}
